micronaut:
  application:
    name: expenseTracker
    server:
      port: 9000
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/expense-tracker
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
liquibase:
  datasources:
    default:
      change-log: 'classpath:liquibase-changelog.xml'